site_name: Portal Acadêmico Fatec
site_description: Materiais de Aula e Recursos Didáticos
site_author: Thissiany Almeida

theme:
name: material
language: pt-BR

palette:
- scheme: default
primary: black
accent: red

features:
- navigation.tabs
- navigation.sections
- navigation.top
- search.highlight
- content.code.copy

extra_css:

- assets/stylesheets/extra.css

nav:

- Início: index.md
