nome: Algoritmos e Lógica de Programação
sigla: ALP

curso: Desenvolvimento de Software Multiplataforma

semestre: 1º semestre

carga_horaria: 80 horas

professora: Profª Me. Thissiany Almeida

github: https://github.com/SEU_USUARIO/materialAula-ALP

github_pages: https://SEU_USUARIO.github.io/materialAula-ALP/

icone: material-code-braces

imagem: alp.png

status: Ativa

ano: 2026
